# Generated by Django 4.1.2 on 2024-07-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_servicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
