# Generated by Django 4.1.2 on 2024-07-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayomcween', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
